# RECAPTCHA_SITE_KEY: "6LflC6cdAAAAAOZeCDsg7ImXtta3bg4q-DG5poJ1"

# RECAPTCHA_SECRET_KEY: "6LflC6cdAAAAADcR1BYQB_SGeXBJZ5nf_e8u8qb1"

# config/initializers/recaptcha.rb
Recaptcha.configure do |config|
  config.site_key   = Rails.application.secrets[:RECAPTCHA_SITE_KEY]
  config.secret_key = Rails.application.secrets[:RECAPTCHA_SECRET_KEY]
  # Uncomment the following line if you are using a proxy server:
  # config.proxy = 'http://myproxy.com.au:8080'
end

development:
  
  
  recaptcha_site_key: 6LflC6cdAAAAAOZeCDsg7ImXtta3bg4q-DG5poJ1
  recaptcha_secret_key: 6LflC6cdAAAAADcR1BYQB_SGeXBJZ5nf_e8u8qb1


